CREATE TABLE Roles (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE
);

CREATE TABLE Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Login TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    FullName TEXT NOT NULL,
    RoleId INTEGER NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Statuses (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE
);

CREATE TABLE Categories (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE
);

CREATE TABLE Requests (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Description TEXT,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AuthorId INTEGER NOT NULL,
    AssigneeId INTEGER,
    StatusId INTEGER NOT NULL,
    CategoryId INTEGER NOT NULL,
    FOREIGN KEY (AuthorId) REFERENCES Users(Id),
    FOREIGN KEY (AssigneeId) REFERENCES Users(Id),
    FOREIGN KEY (StatusId) REFERENCES Statuses(Id),
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
);

CREATE TABLE Comments (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    RequestId INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    Text TEXT NOT NULL,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RequestId) REFERENCES Requests(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE RequestHistory (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    RequestId INTEGER NOT NULL,
    ChangedBy INTEGER NOT NULL,
    OldStatusId INTEGER,
    NewStatusId INTEGER,
    ChangedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RequestId) REFERENCES Requests(Id),
    FOREIGN KEY (ChangedBy) REFERENCES Users(Id)
);